# Generated by Django 5.0.1 on 2024-01-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=128, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=128, verbose_name="Last name"),
                ),
            ],
        ),
    ]
